#
# Update the versions in this file.
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds
  - argo-eventbus-sa.yaml
  - rbac
  - eventbus-controller

images:
  - name: quay.io/argoproj/argo-eventbus
    newTag: latest

