apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-eventbus-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-eventbus-role
subjects:
  - kind: ServiceAccount
    name: argo-eventbus-sa
