apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - rbac

namespace: argo-eventbus

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args
        value: ['--namespaced']
    target:
      kind: Deployment
